### PR TITLE
Fix crash when decoding conflicting events (identical signatures, differently indexed args)

### LINKED ISSUE #132: expectEvent crashes when decoding conflicting events (identical signatures, differently indexed args)
Currently I run in this bug while trying to use expectEvent:

```
(node:26057) UnhandledPromiseRejectionWarning: Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
    at ABICoder.decodeParameters (/home/ricardo/Documents/GitHub/status-im/ens-usernames/node_modules/web3-eth-abi/src/index.js:239:15)
    at ABICoder.decodeLog (/home/ricardo/Documents/GitHub/status-im/ens-usernames/node_modules/web3-eth-abi/src/index.js:302:52)
    at logs.filter.map.log (/home/ricardo/Documents/GitHub/status-im/ens-usernames/node_modules/@openzeppelin/test-helpers/src/expectEvent.js:135:30)
    at Array.map (<anonymous>)
    at decodeLogs (/home/ricardo/Documents/GitHub/status-im/ens-usernames/node_modules/@openzeppelin/test-helpers/src/expectEvent.js:135:6)
    at Function.inTransaction (/home/ricardo/Documents/GitHub/status-im/ens-usernames/node_modules/@openzeppelin/test-helpers/src/expectEvent.js:96:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:26057) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 98)
(node:26057) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is caused when the decoder tries to decode events of a transaction which have identical signature but different indexed parameters.

Consider the following use-case:

Contract that accept ERC20 tokens as payment and mints ERC721 tokens. 
When the ERC20 token is transfered to the contract, a event is emmited by the ERC20 token: `event Transfer(address indexed from, address indexed to, uint256 value);`
Then the contract mints the ERC721 token: `event Transfer(address indexed from, address indexed to, uint256 indexed tokenId);`

```solidity

// SPDX-License-Identifier: CC0-1.0

pragma solidity 0.6.2;

import "../openzeppelin-solidity/token/ERC721/ERC721.sol";
import "../openzeppelin-solidity/token/ERC20/ERC20.sol";


contract ERC20BuyERC721Mint is ERC721 {
    ERC20 public token;

    constructor(ERC20 _token) ERC721("TEST", "Test"){
        token = _token;
    }

    function buy(){
        token.transferFrom(msg.sender,address(this), 1);
        _mint(msg.sender, uint256(msg.sender));
    }
}
```

```js
     const buyResult = await ERC20BuyERC721Mint.methods.buy().send();
     expectEvent.inTransaction(buyResult.transactionHash, ERC20, 'Transfer') //errors here
```

This causes a bug in the expectEvent decoder.

### PR DESCRIPTION
**Pull request by 3esmit**
Fixes #132

This PR change list:
- package.json>dependencies>web3: updated from 1.2.1 to 1.2.5;
- package.json>dependencies>truffle: updated from 5.0.29 to 5.1.46;
- src>expectEvent.js>inTransaction>decodeLogs: if emitter.address is defined, filter by log.address === emitter.address;
- docs>api>expectEvent>inTransaction: note about using the deployed instance emitting the expected event;
- contracts>EventEmitter: new events IndexedConflictingUint, IndexedUint;
- contracts>IndirectEventEmitter: new events IndexedConflictingUint, IndexedUint;
- tests>expectEvent>default: indexed values;
- tests>expectEvent>default: conflicting indexed values;
- tests>expectEvent>inTransaction: using deployed instance (emitter object);
- tests>expectEvent>inTransaction: using non-deployed instance (emitter class);
- tests>expectEvent>inTransaction: using wrong deployed instance;
- tests>expectEvent>inTransaction: indexed values in directly called contract using emitter object;
- tests>expectEvent>inTransaction: indexed values in indirectly called contract using emitter object;
- tests>expectEvent>inTransaction: indexed values in directly called contract using emitter class;
- tests>expectEvent>inTransaction: indexed values in indirectly called contract using emitter class;
- tests>expectEvent>inTransaction: conflicting indexed values in directly called contract using emitter object;
- tests>expectEvent>inTransaction: conflicting indexed values in indirectly called contract using emitter object;
- tests>expectEvent>inTransaction: conflicting indexed values in directly called contract using emitter class;
- tests>expectEvent>inTransaction: conflicting indexed values in indirectly called contract using emitter class.

### CODE REVIEW

**Comment by 3esmit** [comment]
@nventuro Please, review.

Do you think we should add test cases for this specific scenario?

**Comment by 3esmit** [comment]
I noticed it breaks some tests, I am investigating what happened. Seems like there is some problem with contructor events that use a different "emmiter" address than it should.

**Comment by 3esmit** [comment]
Ok, I fixed the errors. 

Some problems I noticed in the test.. For inConstructor it passes the emitter.constructor... IMO this is wrong, because the emitted event must be from the constructed contract, not from its constructor.

Some tests use the "non deployed object" instead of the deployed one, any reason for doing that? 

Anyway, I changed the code to be backwards compatible with the current behavior, so inTransaction don't needs an deployed object to be passed, but when it passes an deployed object, it also checks for the event coming from that exact object.

I'll be adding test cases for the new behavior in the next commit.

**Comment by 3esmit** [comment]
openzeppelin-test-helpers need updated web3 and truffle.

Minimal web3 version is 1.2.5, see https://github.com/ethereum/web3.js/blob/1.x/CHANGELOG.md#125 `Fix crash when decoding events with identical signatures, differently indexed args (#3272)` https://github.com/ethereum/web3.js/issues/3272

For truffle, they don't have a changelog file, so I cannot see where they fixed this issue. Therefore I simply bumped truffle to latest.

**Comment by 3esmit** [comment]
To see what it changes, you can apply this diff to undo the expectEvent.js changes from this commit:

[undo_expectEvent_changes.txt](https://github.com/OpenZeppelin/openzeppelin-test-helpers/files/5309839/undo_expectEvent_changes.txt)

Note: I added await in the method that reads indexed conflicting event, because if it's not await the error is thrown in a async which marks the wrong test as failing.

**Comment by 3esmit** [comment]
I added some notes to the docs instructing to always use the deployed instance that emmited the event. Maybe would be better if all tests use `this.emitter` and `this.secondEmitter` just to use the suggested behavior in docs.

Also, note that this PR changes a behavior that was not covered under tests: If someone uses a different deployed contract instance than the one that emitted the event it will not find the event, before this PR it would find the event as the address of the contract was not considered in the filter. 
I added the coverage to this scenario, as now this is a specified behavior.

**Comment by 3esmit** [comment]
Diff file for undo changes in `src/expectEvent.js`:
[beforechanges_expectEvent.diff.txt](https://github.com/OpenZeppelin/openzeppelin-test-helpers/files/5310719/beforechanges_expectEvent.diff.txt)

With the above diff applied. the result of `npm run test > beforechanges_expectEvent_tests.log.txt`
[beforechanges_expectEvent_tests.log.txt](https://github.com/OpenZeppelin/openzeppelin-test-helpers/files/5310721/beforechanges_expectEvent_tests.log.txt)

**Comment by frangio** [comment]
Thank you @3esmit. I will review this as soon as possible.

File: src/expectEvent.js [hunk 1]
```diff
@@ -108,10 +108,17 @@ async function notInTransaction (txHash, emitter, eventName) {
 // the same form truffle-contract uses on its receipts
 function decodeLogs (logs, emitter, eventName) {
   let abi;
+  let address;
   if (isWeb3Contract(emitter)) {
     abi = emitter.options.jsonInterface;
+    address = emitter.options.address;
   } else if (isTruffleContract(emitter)) {
     abi = emitter.abi;
+    try {
```
Comment (frangio) [inline src/expectEvent.js:117]: What exception is this `try` block meant to catch? Wouldn't `emitter.address` just be `undefined` and result in `address = undefined`?

File: package.json [hunk 2]
```diff
@@ -45,8 +45,8 @@
     "ethjs-abi": "^0.2.1",
     "lodash.flatten": "^4.4.0",
     "semver": "^5.6.0",
-    "web3": "^1.2.1",
-    "web3-utils": "^1.2.1"
+    "web3": "^1.2.5",
+    "web3-utils": "^1.2.5"
```
Comment (frangio) [inline package.json:49]: Are these dependency upgrades necessary for the feature?

File: contracts/EventEmitter.sol [hunk 3]
```diff
@@ -16,6 +16,8 @@ contract EventEmitter {
     event LongUintBooleanString(uint256 uintValue, bool booleanValue, string stringValue);
     event Bytes(bytes value);
     event StringArray(string[] value);
+    event IndexedConflictingUint(uint256 indexed indexedValue, uint256 normalValue);
```
Comment (frangio) [inline contracts/EventEmitter.sol:19]: Can you explain the choice of event argument names here as well as in `IndirectEventEmitter`?

Is there a specific reason why in this case `normalValue` is the second argument and is the first in the indirect contract?

**Review by frangio — COMMENTED** [review]
Thank you @3esmit. I appreciate the thorough testing.

I'm trying to figure out if this change is backwards compatible or breaking. What do you think?

File: src/expectEvent.js (hunk 1 above)
Comment (3esmit) [reply src/expectEvent.js:117]: Yes, if the contract emitter address is null it throws, therefore it needs this try catch, maybe could be replaced with a ifelse.

Comment (3esmit) [reply src/expectEvent.js:117]: Ah, this happens when the expectEvent function is used with a "contract artifact class" (no deploy address). This was added to ensure backwards compatibility, so tests don't need to be changed to use an artifact with a deployed address, this is only needed for when there is conflicting indexed events.

File: test/src/expectEvent.truffle.test.js [hunk 4]
```diff
@@ -463,12 +523,161 @@ contract('expectEvent (truffle contracts)', function ([deployer]) {
...
+      context('with directly called contract', function () {
+        it('accepts emitted events with correct indexed parameter and emitter object', async function () {
+          expectEvent.inTransaction(this.txHash, this.emitter, 'IndexedUint', {
+            indexedValue: this.indexedValue,
+            normalValue: this.normalValue,
+          });
         });
+
+        it('accepts emitted indexed events with correct indexed parameter and emitter class', async function () {
+          expectEvent.inTransaction(this.txHash, EventEmitter, 'IndexedUint', {
```
Comment (3esmit) [inline test/src/expectEvent.truffle.test.js:571]: Here it does the try catch and finds emitter address null.

File: test/src/expectEvent.truffle.test.js [hunk 5]
```diff
@@ -463,12 +523,161 @@ contract('expectEvent (truffle contracts)', function ([deployer]) {
...
+          this.indexedValue2,
+          this.normalValue2,
+          this.secondEmitter.address
+        );
+        this.txHash = receipt.transactionHash;
+      });
+
+      context('with directly called contract', function () {
+        it('accepts emitted events with correct indexed parameter and emitter object', async function () {
+          expectEvent.inTransaction(this.txHash, this.emitter, 'IndexedUint', {
```
Comment (3esmit) [inline test/src/expectEvent.truffle.test.js:564]: Here it is using n artifact with deployed address, don't throws at emitter.address

File: package.json (hunk 2 above)
Comment (3esmit) [reply package.json:49]: Yes.  See changelog https://github.com/ethereum/web3.js/blob/1.x/CHANGELOG.md#125

File: contracts/EventEmitter.sol (hunk 3 above)
Comment (3esmit) [reply contracts/EventEmitter.sol:19]: This is to more clearly show/test the conflict. However the names are irrelevant, the only important thing is the number of indexed parameters in the indirect emitter to be more than in the direct emitter.

**Comment by 3esmit** [comment]
> Thank you @3esmit. I appreciate the thorough testing.
> 
> I'm trying to figure out if this change is backwards compatible or breaking. What do you think?

They are compatible. You can see that in the tests I didn't changed other tests, I just included new tests for the indexed events and indexed events conflicts.

The compatibility is ensured by a try catch and former behavior when using a contract artifact class.

File: test/src/expectEvent.truffle.test.js [hunk 6]
```diff
@@ -463,12 +523,161 @@ contract('expectEvent (truffle contracts)', function ([deployer]) {
...
+        it('throws if the emitter class is passed', async function () {
+          await assertFailure(expectEvent.inTransaction(this.txHash, EventEmitter, 'IndexedConflictingUint', {
+            indexedValue: this.indexedValue,
+            normalValue: this.normalValue,
+          }));
+        });
+
+        it('throws if the event value emitted from other contract is passed', async function () {
+          await assertFailure(expectEvent.inTransaction(this.txHash, this.emitter, 'IndexedConflictingUint', {
+            indexedValue: this.normalValue,
```
Comment (3esmit) [inline test/src/expectEvent.truffle.test.js:626]: This is why the parameters names of the indexed event are different, so I can do this type of checks.

File: contracts/IndirectEventEmitter.sol [hunk 7]
```diff
@@ -2,8 +2,18 @@ pragma solidity ^0.5.0;
 
 contract IndirectEventEmitter {
     event IndirectString(string value);
+    event IndexedConflictingUint(uint256 indexed normalValue, uint256 indexed indexedConflictValue);
```
Comment (frangio) [inline contracts/IndirectEventEmitter.sol:5]: Following up on the discussion about argument names. I think I'm just confused because here `normalValue` is actually indexed, and elsewhere `normalValue` is used for non-indexed arguments.

Can you rename this `nomalValue` to `indexedValue` or something else?

**Comment by 3esmit** [comment]
> > The compatibility is ensured by a try catch and former behavior when using a contract artifact class.
> 
> But if someone was using `expectEvent.inTransaction` with a contract instance with address as the emitter, there seems to be a possibility that this update would break their tests. Is that true?

No, it won't break tests that use a contract instance without address. A contract instance with address is only required when there is a conflicting event.

File: contracts/IndirectEventEmitter.sol (hunk 7 above)
Comment (3esmit) [reply contracts/IndirectEventEmitter.sol]: Ok, I changed from

EventEmitter:
indexedValue -> indexedValue1
normalValue -> normalValue1

IndirectEventEmitter:
normalValue -> indexedValue2
indexedConflictValue-> indexedValue3

I agree that reusing name "normalValue" was confusing. I didn't wanted to repeat the indexedValue from the other contract, because I want to test specifically requesting the wrong event (with the wrong arg names).

**Comment by 3esmit** [comment]
> **Edit:** I see that you referenced this issue in one of your comments. So there is a breaking change but we can say that the previous behavior had a bug because it would recognize contracts not emitted by the specified `emitter`.

This is interesting, perhaps I should make tests for repeated events from multiple indirect emitters and direct emitters, and the use of the instance with address makes it able to select what event, while using the instance without address captures all events.

**Comment by 3esmit** [comment]
Perhaps it would be interesting to add another change to the expectEvent, a try-catch in the decodeLogs, this will enable the use of contract instance without address for conflicting events.

File: test/src/expectEvent.truffle.test.js [hunk 8]
```diff
@@ -463,12 +525,163 @@ contract('expectEvent (truffle contracts)', function ([deployer]) {
...
+          await assertFailure(expectEvent.inTransaction(this.txHash, this.emitter, 'IndexedConflictingUint', {
+            normalValue: this.normalValue,
+            indexedValue2: this.indexedValue2,
+          }));
+        });
+
+        it('throws if the wrong event is requested', async function () {
+          await assertFailure(expectEvent.inTransaction(this.txHash, this.secondEmitter, 'IndexedConflictingUint', {
+            indexedValue2: this.indexedValue1,
+            indexedValue3: this.normalValue1,
```
Comment (3esmit) [inline test/src/expectEvent.truffle.test.js:645]: See here, this is a test to ensure that expectEvent is not accepting events if using the ABI of another. I was not sure if this is really necessary, but I added it as it looks a plausible test to be done for checking if the events are being returned correctly.

**Review by frangio — APPROVED** [review]
Thank you @3esmit!
